# Generated by Django 4.1.2 on 2022-10-09 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_validity', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('distance', models.IntegerField()),
                ('first_stop', models.IntegerField()),
                ('last_stop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LineShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('WD', 'Weekday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('daytime', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Night')], max_length=1)),
                ('order', models.IntegerField(null=True)),
                ('line', models.ManyToManyField(to='management_app.line')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MINIBUS', 'Minibus'), ('BUS', 'Standard bus'), ('ARTICULATED BUS', 'Articulated Bus'), ('SHORT TRAM', 'Short Tram'), ('LONG TRAM', 'Long Tram')], max_length=30)),
                ('engine', models.CharField(choices=[('E', 'Electric'), ('D', 'Diesel'), ('H', 'Hybrid')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('capacity', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_number', models.CharField(max_length=10)),
                ('plate', models.CharField(max_length=10)),
                ('production_date', models.DateField()),
                ('last_review', models.DateField()),
                ('next_review', models.DateField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('overtime', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.driver')),
                ('shift_daytime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.lineshift')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='vehicle_type',
            field=models.ManyToManyField(to='management_app.vehicletype'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('position', models.CharField(max_length=30)),
                ('contract', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('FR', 'Freelancer')], max_length=2)),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField(default='9999-12-31')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management_app.employee'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.vehicle'),
        ),
    ]
