# Generated by Django 4.1.2 on 2022-10-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='first_stop',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='line',
            name='last_stop',
            field=models.CharField(max_length=50),
        ),
    ]
