# Generated by Django 4.1.2 on 2022-10-15 12:38

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_alter_line_first_stop_alter_line_last_stop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': [django.db.models.functions.comparison.Cast('name', output_field=models.IntegerField())]},
        ),
    ]
