# Generated by Django 4.1.2 on 2022-10-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0003_alter_line_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineshift',
            name='shift_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
