# Generated by Django 4.1.2 on 2022-10-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_lineshift_shift_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineshift',
            name='shift_number',
        ),
    ]
