# Generated by Django 4.1.2 on 2022-10-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0005_remove_lineshift_shift_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineshift',
            name='order',
        ),
        migrations.AddField(
            model_name='lineshift',
            name='number_of_shifts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
