# Generated by Django 4.1.2 on 2022-10-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0006_remove_lineshift_order_lineshift_number_of_shifts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineshift',
            name='number_of_shifts',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='order',
        ),
        migrations.AddField(
            model_name='lineshift',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
