# Generated by Django 4.1.2 on 2022-10-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0007_remove_lineshift_number_of_shifts_remove_shift_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
