# Generated by Django 4.1.2 on 2022-10-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0008_shift_shift_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineshift',
            name='nuumber_of_shifts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_number',
            field=models.IntegerField(null=True),
        ),
    ]
