# Generated by Django 4.1.2 on 2022-10-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0009_lineshift_nuumber_of_shifts_alter_shift_shift_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftOnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_shifts', models.IntegerField(null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.line')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('WD', 'Weekday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('daytime', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Night')], max_length=1)),
                ('order', models.IntegerField(null=True)),
                ('line', models.ManyToManyField(through='management_app.ShiftOnLine', to='management_app.line')),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='shift_daytime',
        ),
        migrations.DeleteModel(
            name='LineShift',
        ),
        migrations.AddField(
            model_name='shiftonline',
            name='shift_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.shifttime'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_on_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.shiftonline'),
        ),
    ]
