# Generated by Django 4.1.2 on 2022-10-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0015_alter_line_name_alter_shift_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='side_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
