# Generated by Django 4.1.2 on 2022-10-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0017_remove_line_vehicle_type_linevehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='vehicle_type',
            field=models.ManyToManyField(blank=True, through='management_app.LineVehicleType', to='management_app.vehicletype'),
        ),
    ]
