# Generated by Django 4.1.2 on 2022-10-17 13:33

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0018_line_vehicle_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': [django.db.models.functions.comparison.Cast('side_number', output_field=models.IntegerField())]},
        ),
    ]
